# (C) Copyright 2020, 2021, 2022, 2023, 2024 IBM. All Rights Reserved.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

notifications:
  email: false

# Disable double triggering when issuing a PR from a branch in the main repo.
branches:
  only:
    - "main"
    - /^release\/.*$/

stages:
  - Test and lint
  - Test multiple python versions

# Parent stage definition, to avoid copy-pasting.
job_install_common: &job_install_common
  os: linux
  dist: focal
  language: python
  before_install:
    - sudo apt-get -qq install -y ca-certificates
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
  install:
    # Set the python executable, to force cmake picking the right one.
    - PYTHON_EXECUTABLE=~/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/python$TRAVIS_PYTHON_VERSION
    - $PYTHON_EXECUTABLE -m pip install travis-wait-improved
    - travis-wait-improved --timeout 60m $PYTHON_EXECUTABLE -m pip install aihwkit
    - travis-wait-improved --timeout 60m $PYTHON_EXECUTABLE -m pip install -r requirements.txt
    - $PYTHON_EXECUTABLE -m pip install -r requirements_dev.txt
    # Install the package in editable mode.
    - VERBOSE=1 $PYTHON_EXECUTABLE -m pip install -v -e .
    - travis-wait-improved --timeout 60m $PYTHON_EXECUTABLE -m pip install -U --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly

  script:
    - $PYTHON_EXECUTABLE -c "import triton; print(triton.__version__)"

build_deploy_common: &build_deploy_common
  deploy:
    provider: s3
    access_key_id: $COS_ACCESS_KEY_ID
    secret_access_key: $COS_SECRET_ACCESS_KEY
    bucket: $COS_BUCKET
    skip_cleanup: true
    local_dir: wheelhouse
    endpoint: https://$COS_ENDPOINT
    on:
      all_branches: true

jobs:
  include:
  - name: "Install and test. Python 3.10"
    <<: *job_install_common
    stage: Test
    python: "3.10"
    script:
      - make pytest

  - name: "Install, pycodestyle, lint, and mypy. Python 3.10"
    <<: *job_install_common
    stage: Test and lint
    python: "3.10"
    script:
      - make pycodestyle
      - make pylint
      - make mypy